### ISSUE TITLE
undefined method error when running git-conflict-blame

### ISSUE THREAD

**Issue by kingmaiku** [eterry1388/git-conflict-blame#1]
git-conflict-blame 

```
NoMethodError: undefined method `[]' for nil:NilClass
/home/msquire/.rvm/gems/ruby-2.2.1/gems/git-conflict-blame-0.4.0/lib/git-conflict-blame.rb:127:in `block in conflicts'
/home/msquire/.rvm/gems/ruby-2.2.1/gems/git-conflict-blame-0.4.0/lib/git-conflict-blame.rb:127:in `map'
/home/msquire/.rvm/gems/ruby-2.2.1/gems/git-conflict-blame-0.4.0/lib/git-conflict-blame.rb:127:in `conflicts'
/home/msquire/.rvm/gems/ruby-2.2.1/gems/git-conflict-blame-0.4.0/lib/git-conflict-blame.rb:31:in `run!'
/home/msquire/.rvm/gems/ruby-2.2.1/gems/git-conflict-blame-0.4.0/lib/git-conflict-blame.rb:24:in `run'
/home/msquire/.rvm/gems/ruby-2.2.1/gems/git-conflict-blame-0.4.0/bin/git-conflict-blame:34:in `<top (required)>'
/home/msquire/.rvm/gems/ruby-2.2.1/bin/git-conflict-blame:23:in `load'
/home/msquire/.rvm/gems/ruby-2.2.1/bin/git-conflict-blame:23:in `<main>'
/home/msquire/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/home/msquire/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
Unhandled exception! This is probably a bug. Please log it here:
https://github.com/eterry1388/git-conflict-blame/issues
```

**Comment by eterry1388** [comment]
I was able to reproduce this.  Looks like the issue is when conflicted files are in a "deleted by us" state.  For example:

```
    deleted by us:      file1
    deleted by us:      file2
    both modified:      file3
    both modified:      file4
    both modified:      file5
```
